version: "3.8"

services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
