version: "3.8"

services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1G

volumes:
  mysql_data:
