CREATE TABLE instance_events (
    event_type Enum('CREATED' = 1, 'UPDATED' = 2, 'DELETED' = 3),
    timestamp DateTime,
    project_id UUID,
    uuid UUID,
    type LowCardinality(String),
    state Enum('ACTIVE' = 1,
               'REBOOT' = 2,
               'HARD_REBOOT' = 3,
               'PASSWORD' = 4,
               'REBUILD' = 5,
               'MIGRATING' = 6,
               'RESIZE' = 7,
               'VERIFY_RESIZE' = 8,
               'REVERT_RESIZE' = 9,
               'PAUSED' = 10,
               'SUSPENDED' = 11,
               'RESCUE' = 12,
               'ERROR' = 13,
               'DELETED' = 14,
               'SOFT_DELETED' = 15,
               'SHELVED' = 16,
               'SHELVED_OFFLOADED' = 17,
               'BUILD' = 18,
               'SHUTOFF' = 19),
    image UUID
) ENGINE = MergeTree()
ORDER BY (project_id, type, state, image, timestamp);
